replicaCount: 1

image:
  repository: ghcr.io/tom1299/trivy-processor
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

config:
  TRIVY_PROCESSOR_LOG_LEVEL: "info"
  TRIVY_PROCESSOR_NAMESPACE: "default"
